apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-server
  labels:
    app: py-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py-server
  template:
    metadata:
      labels:
        app: py-server
    spec:
      containers:
      - name: py-server
        image: vishnusk/py-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8765
---
apiVersion: v1
kind: Service
metadata:
  name: py-service
  labels:
    app: py-service
spec:
  ports:
  - port: 8765
    protocol: TCP
  selector:
    app: py-server
  type: LoadBalancer
